# start up
/run/initialize
#
# open an OpenGL viewer
/vis/open OGL
#
# draw geometry
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointVector -1 0 0
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
#
# draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# Make the "World" box invisible
#/vis/geometry/set/visibility World 0 false
#
# Superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
/vis/scene/add/axes